name: GCToolKit build with Maven

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'    
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
env: 
  CACHE: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      if: ${{!CACHE}}
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      if: ${{CACHE}}
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
        cache: 'maven'
        
    - name: Build with Maven
      run: ./mvnw -B verify --file pom.xml 
